name: "Hello"
on:
  pull_request:
    types: [labeled]
  push:
    branches:
    - master

jobs:
  hello:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - run: echo $ref
      env: 
        ref: ${{ github.ref }}
    - run: echo $test
      env: 
        test: ${{ contains(github.event.pull_request.labels.*.name , 'ready_for_qa') }}